feat: add multilanguage names for connectivity environment WIP
withthegrid/platform-sdk pull request #228
Opened 2022-05-31 11:42 UTC by srieding

refs: withthegrid/platform#1255

2022-05-31 11:48 UTC, srieding commented on src/models/command-type.ts
> +  name: stringOrTranslationsSchema.required().example('Measurement cycle'),
This ends up in the get but also in the find route.

2022-06-01 07:34 UTC, everhardt requested changes

2022-06-01 07:34 UTC, everhardt commented on src/models/command-type.ts
> +  name: stringOrTranslationsSchema.required().example('Measurement cycle'),
`name` should be string for apiVersion <= 6 (also applicable to other cases in this PR)

2022-06-01 09:21 UTC, everhardt commented on src/models/string-or-translations.ts
> +  if (name === null) {
But you can't provide title as the `name` parameter for this function, right? My point is that `StringOrTranslations` does not contain `null`.

2022-06-01 09:49 UTC, srieding commented on src/models/string-or-translations.ts
> +  if (name === null) {
Hmm, that is technically correct though not enforced in the frontend code. So I ended up calling this with null and undefined from the frontend. I could of course make a separate function for that usecase

2022-06-01 09:59 UTC, everhardt commented on src/models/string-or-translations.ts
> +  if (name === null) {
Maybe the function overloading can help out here as well..

2022-06-16 14:11 UTC, everhardt approved these changes
Can be merged when https://github.com/withthegrid/platform/pull/1319/ is ready

2022-06-17 07:25 UTC, merged