feat: grid layout for analytics panel
withthegrid/platform-sdk pull request #71
Opened 2021-10-24 09:09 UTC by yarsky-tgz

Part of withthegrid/platform-client#621

2021-11-02 18:17 UTC, yarsky-tgz commented
updated, final version

2021-11-03 13:53 UTC, everhardt commented
I don't see any errors, but it might be that there is some overspecification, take for example
the following array of card positions:
```ts
[
  { x: 0, y: 0, width: 2, height: 2 },
  { x: 1, y: 1, width: 3, height: 3 },
]
```

Those would overlap, while that is not possible. It depends on the actual implementation in platform-client whether this is a problem and if we want to avoid it or accept it.

2021-11-08 12:33 UTC, yarsky-tgz commented
> I don't see any errors, but it might be that there is some overspecification, take for example the following array of card positions:
> 
> ```ts
> [
>   { x: 0, y: 0, width: 2, height: 2 },
>   { x: 1, y: 1, width: 3, height: 3 },
> ]
> ```
> 
> Those would overlap, while that is not possible. It depends on the actual implementation in platform-client whether this is a problem and if we want to avoid it or accept it.

I've added overlapping validation to Joi and tested it, works nice

2021-11-08 12:41 UTC, everhardt commented
Haha, alright! Note that https://github.com/withthegrid/platform/issues/782 is still around the corner ;).

2021-11-24 09:46 UTC, everhardt requested changes
One small request and a comment on complexity that you can ignore ;).

2021-11-24 09:46 UTC, everhardt commented on src/routes/analytics/add-panel.ts
> +    layouts: layoutsSchema.allow(null).empty(null).default(),
`.allow(null).empty(null)` is already in `layoutsSchema`. Also, if my comment there makes sense, we can also drop `.default()` I think.

2021-11-24 09:46 UTC, everhardt commented on src/models/analytics-panel.ts
> +  .custom((layout: CardPosition[], helper) => {
I struggle a bit with adding this kind of complexity to the sdk (like we also have at [BaseFieldConfiguration](https://github.com/withthegrid/platform-sdk/blob/0ebbe8fcdfa8af013ec36282e475022a79c20fec/src/models/fields/base-field-configuration.ts#L26) for example), but don't have a better alternative at the moment. Therefore let's go for this and if we see an opportunity to simplify, we can do that later.

2021-11-24 10:42 UTC, yarsky-tgz commented on src/models/analytics-panel.ts
> +}).allow(null).empty(null);
`null` comes from database by default. Then it's replaced by Joi.

2021-11-24 10:47 UTC, yarsky-tgz commented on src/models/analytics-panel.ts
> +}).allow(null).empty(null);
Actually it only saves us from data migration for already existing dashboards. 

May be as alternative default value can be set through schema, if it's better.

2021-11-24 10:49 UTC, everhardt commented on src/models/analytics-panel.ts
> +}).allow(null).empty(null);
I see. Can't we better hide that logic in the platform repo? That we map a `null` to `undefined` there, so that we keep this public API clean?

2021-11-25 18:12 UTC, yarsky-tgz commented on src/models/analytics-panel.ts
> +}).allow(null).empty(null);
Not actual already. I've dropped responsive layouts and updated routes.

2021-12-03 08:45 UTC, everhardt commented
Cool! Made one simplification (no `null` in layout)

2021-12-03 08:45 UTC, merged